# start with the official R project base image
FROM rocker/r-apt:bionic

# copy this github repo into the Docker image and set as the working directory
COPY . /usr/local/src/myscripts
WORKDIR /usr/local/src/myscripts

# Install the C/C++ libraries needed to run the script
RUN apt-get update \
   && apt-get install -y --no-install-recommends \
libssl-dev \
libcurl4-openssl-dev \
libxml2-dev

# Install the R libraries needed to run the scripts

RUN apt-get update && \
    apt-get install -y -qq \
    	r-cran-dplyr \
    	r-cran-stringr \
    	r-cran-purrr \
    	r-cran-rcpp \
    	r-cran-shiny
    	
RUN R -e 'install.packages("git2r")'

EXPOSE 8080

# Execute the target script
CMD ["Rscript", "run.R"]